//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermInjectorPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TermInjectorPlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add edit rule collection.
        /// </summary>
        public static string EditRules_AddEditRuleCollectionTitle {
            get {
                return ResourceManager.GetString("EditRules_AddEditRuleCollectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rule collection.
        /// </summary>
        public static string EditRules_AddRuleCollectionButton {
            get {
                return ResourceManager.GetString("EditRules_AddRuleCollectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create post-edit rule.
        /// </summary>
        public static string EditRules_CreatePostEditRuleTitle {
            get {
                return ResourceManager.GetString("EditRules_CreatePostEditRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create edit rule.
        /// </summary>
        public static string EditRules_CreatePreEditRuleTitle {
            get {
                return ResourceManager.GetString("EditRules_CreatePreEditRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create rule.
        /// </summary>
        public static string EditRules_CreateRuleButton {
            get {
                return ResourceManager.GetString("EditRules_CreateRuleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete rule.
        /// </summary>
        public static string EditRules_DeleteRuleButton {
            get {
                return ResourceManager.GetString("EditRules_DeleteRuleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete rule collection.
        /// </summary>
        public static string EditRules_DeleteRuleCollectionButton {
            get {
                return ResourceManager.GetString("EditRules_DeleteRuleCollectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rule.
        /// </summary>
        public static string EditRules_EditRuleButton {
            get {
                return ResourceManager.GetString("EditRules_EditRuleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rule collection.
        /// </summary>
        public static string EditRules_EditRuleCollectionButton {
            get {
                return ResourceManager.GetString("EditRules_EditRuleCollectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rules in collection {0}.
        /// </summary>
        public static string EditRules_EditRuleCollectionTitle {
            get {
                return ResourceManager.GetString("EditRules_EditRuleCollectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermInjector settings.
        /// </summary>
        public static string EditRules_EditRulesHeading {
            get {
                return ResourceManager.GetString("EditRules_EditRulesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rules for model {0}.
        /// </summary>
        public static string EditRules_EditRulesTitle {
            get {
                return ResourceManager.GetString("EditRules_EditRulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string EditRules_MoveDownButton {
            get {
                return ResourceManager.GetString("EditRules_MoveDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string EditRules_MoveUpButton {
            get {
                return ResourceManager.GetString("EditRules_MoveUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove rule collection.
        /// </summary>
        public static string EditRules_RemoveRuleCollectionButton {
            get {
                return ResourceManager.GetString("EditRules_RemoveRuleCollectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rules.
        /// </summary>
        public static string Main_EditRulesButton {
            get {
                return ResourceManager.GetString("Main_EditRulesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to permanently delete rule collection {0}? This collection may be in use with other models, and it will also be deleted from those models..
        /// </summary>
        public static string Rules_DeleteRuleCollectionConfirmation {
            get {
                return ResourceManager.GetString("Rules_DeleteRuleCollectionConfirmation", resourceCulture);
            }
        }
    }
}
